version: "3"

services:
  nginx:
    image: nginx:1.14.0
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/home/user/www/project/web
      - /var/run/php/php7.4-fpm.sock:/var/run/php/php7.4-fpm.sock

  redis:
    image: redis:4.0.9
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: '--appendonly yes'
  
  mongo:
    image: mongo:3.6.3
    ports:
       - 27017:27017
    volumes:
      - mongo-data:/data/db


  postgres:
    image: postgres:10.12
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres


  mysql:
    image: mysql:5.7.30
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root

volumes:
    redis-data:
    mongo-data:
    postgres-data:
    mysql-data: